apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music01
  creationTimestamp: null
  name: spring-music01.apps.local.20240708.157.21940
spec:
  refName: spring-music01.apps.local
  releasedAt: "2024-07-08T01:58:48Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/spring-music01@sha256:edb15c7181bb9948cdd27c8d9eecd2d2abc3e0fbc8d7d046ba393e0c7f633a1d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240708.157.21940
