apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music01
  creationTimestamp: null
  name: spring-music01.apps.local.20240708.1824.21701
spec:
  refName: spring-music01.apps.local
  releasedAt: "2024-07-08T18:25:57Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/spring-music01@sha256:03a2017fd3189e5915b7fde57d10e021b4e9369c0df09879482d6ca58f2c6e46
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240708.1824.21701
