apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music01
  creationTimestamp: null
  name: spring-music01.apps.local.20240724.2102.35140
spec:
  refName: spring-music01.apps.local
  releasedAt: "2024-07-24T21:04:02Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/spring-music01@sha256:3a0c97905a8ffd895e11e19982ddc81bb10196d40ddf61a7e83376198eec5073
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240724.2102.35140
