apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-int-space
  namespace: argocd
spec:
  destination:
    name: 'sa-tanzu-platform:AMER-West:space:gitops-int'
    namespace: default
    server: ''
  source:
    path: gitops/amer-west/spaces/gitops-int
    repoURL: 'https://github.com/warroyo/tpk8s-argo-gitops-demo'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - Validate=false
    automated:
      prune: false
      selfHeal: false